posts/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('', views.index, name="index"), 
    path('create', views.post_create, name='create'),
    path('feed/', views.feed, name='feed'),
     path('feed2/', views.feed, name='feed2'),
    path('listItems', views.listItems, name='listItems'),
    path('like/<int:id>', views.like_post, name='like'),
    path('posts/<int:id>/', views.detail, name='detail'),
    path('posts/<slug:slug>/', views.detail, name='detail'),
    path('category/<slug:slug>/', views.category_detail, name='category_detail'),
    path('view', views.post_view, name='view'),
    path('add_feed_reply/<int:comment_id>/', views.add_feed_reply, name='add_feed_reply'),
    path('add_reply/<int:comment_id>/', views.add_reply, name='add_reply'),
]

vietForum/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('posts/', include('posts.urls')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.shortcuts import reverse
from hitcount.models import HitCountMixin, HitCount
from django.contrib.contenttypes.fields import GenericRelation
from taggit.managers import TaggableManager

# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length= 400, unique=True, blank=True)
    description = models.TextField(default="description")

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Category, self).save(*args, **kwargs)

    def get_url(self):
        return reverse("post", kwargs={
            "slug":self.slug
        })

    @property
    def num_posts(self):
        return Post.objects.filter(categories=self).count()

    @property
    def last_post(self):
        return Post.objects.filter(categories=self).latest("created")

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    body = models.TextField(blank=True)
    categories = models.ManyToManyField(Category)
    slug = models.SlugField(max_length=200, blank=True)
    created = models.DateField(auto_now_add=True)
    liked_by = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="posts_liked", blank=True)
    hit_count_generic = GenericRelation(HitCount, object_id_field='object_pk',
        related_query_name='hit_count_generic_relation'
    )
    tags = TaggableManager(blank=True)
    # comments = models.ManyToManyField(Comment, blank=True)
    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
            i = 1
            while Post.objects.filter(slug=self.slug).exists():
                self.slug = slugify(self.title) + '-' + str(i)
                i += 1
            super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_url(self):
        return reverse("detail", kwargs={
            "slug":self.slug
        })

    @property
    def num_comments(self):
        return self.comments.count()

    @property
    def last_reply(self):
        return self.comments.latest("created")

class Image(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='images')
    caption = models.TextField()
    images = models.ImageField(upload_to='images/%y/%m/%d', blank=True)
    def __str__(self):
        return self.post.title



class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    body = models.TextField()
    created = models.DateTimeField(auto_now=True)
    posted_by = models.CharField(max_length=100)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return self.body

    @property
    def num_comments(self):
        return self.body.count()

    @property
    def last_reply(self):
        return self.body.latest("created")

class Reply(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='replies')
    body = models.TextField()
    created = models.DateTimeField(auto_now=True)
    posted_by = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "replies"

    def __str__(self):
        return self.body

posts/forms.py
from .models import Post, Image, Comment, Reply
from django import forms


class PostCreateForm(forms.ModelForm):
    class Meta:
        
        model = Post
        fields = ('title', 'body', "categories", "tags")

class ImageForm(forms.ModelForm):
    images = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))
    class Meta:
        model = Image
        fields = ('images', 'caption',)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body', 'posted_by')

class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ('body', 'posted_by')

posts/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from .forms import PostCreateForm, ImageForm, CommentForm, ReplyForm
from .utils import update_views
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from .models import Post, Image, Category
from .models import Comment, Reply
from django.shortcuts import reverse
from django.utils.text import slugify
from users.models import Profile


# Create your views here.
def index(request):
    categories = Category.objects.all()
    posts = Post.objects.all()
    latest_post = Post.objects.latest('created')
    users = Profile.objects.all()
    context = {
        "categories": categories,
        "posts": posts,
        "latest_post": latest_post,
        "users": users,
    }
    return render(request, "posts/index.html", context)

@login_required
def post_create(request):
    if request.method == 'POST':
        # Get the post data from the request
        title = request.POST['title']
        body = request.POST['body']
        categories = request.POST.getlist('categories')
        tags = request.POST.getlist('tags')
        images = request.FILES.getlist('images')
        captions = request.POST.getlist('caption')

        # Create a new post with the given data                                 
        post = Post.objects.create(
            user=request.user,
            title=title,
            body=body
        )

        if not post.slug:
            post.slug = slugify(post.title)
            post.save()
        # Add the categories to the post
        for category in categories:
            cat = Category.objects.get(id=category)
            post.categories.add(cat)

            # Add the tags to the post
        for tag in tags:
            post.tags.add(tag)

        # Add the images to the post
        for i in range(0, len(images)):
            image = Image(post=post, images=images[i], caption=captions[i])
            image.save()
        return redirect('feed')
        # return redirect('../posts/detail', slug=post.slug)
    else:
        # Render the form template to create a new post
        categories = Category.objects.all()
        return render(request, 'posts/create.html', {'categories': categories})

def feed(request):
    # Handle form submission for creating a comment

    if request.method == 'POST':
        comment_form = CommentForm(data= request.POST)
        new_comment = comment_form.save(commit=False)
        post_id = request.POST.get('post_id')
        post = get_object_or_404(Post, id=post_id)
        new_comment.post = post
        new_comment.save()
         # Redirect the user back to the same page after the comment is submitted
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    
    posts = Post.objects.all()
    logged_user = request.user
        
    return render(request, 'posts/feed.html', {'posts': posts, 'logged_user': logged_user})



def like_post(request, id):
    post = Post.objects.get(id=id)
    if post.liked_by.filter(id=request.user.id).exists():
        # print(request.user.username)
        post.liked_by.remove(request.user)
    else:
        post.liked_by.add(request.user)
        print(id, request.user.username, request.user.id)
    return redirect('detail', slug=post.slug)

def category_detail(request, slug):
    category = get_object_or_404(Category, slug=slug)
    posts = Post.objects.filter(categories=category)
    context = {
        'category': category,
        'posts': posts,
    }
    return render(request, 'posts/category_detail.html', context)
    
def listItems(request):
    posts = Post.objects.all()
    logged_user = request.user
    return render(request, 'posts/listItems.html', {'posts': posts, 'logged_user': logged_user,})



def detail(request, id=None, slug=None):
    if request.method == 'POST':
        comment_form = CommentForm(data= request.POST)
        new_comment = comment_form.save(commit=False)
        post_id = request.POST.get('post_id')
        post = get_object_or_404(Post, id=post_id)
        new_comment.post = post
        new_comment.save()
        update_views(request, post)

    if id:
        post = get_object_or_404(Post, pk=id)
    elif slug:
        post = get_object_or_404(Post, slug=slug)

    logged_user = request.user
    context = {
        'post': post,
        'logged_user': logged_user,
    }
    update_views(request, post)
    return render(request, 'posts/detail.html', context)

def add_feed_reply(request, comment_id):
    comment = Comment.objects.get(id=comment_id)
    if request.method == 'POST':
        reply_text = request.POST.get('body')
        posted_by = request.POST.get('posted_by')
        reply = Reply.objects.create(comment=comment, body=reply_text, posted_by = posted_by)
        reply.save()
        print(comment_id)
    # return redirect(reverse('feed'))
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def add_reply(request, comment_id):
    comment = Comment.objects.get(id=comment_id)
    if request.method == 'POST':
        reply_text = request.POST.get('body')
        posted_by = request.POST.get('posted_by')
        reply = Reply.objects.create(comment=comment, body=reply_text, posted_by = posted_by)
        reply.save()
        return redirect('detail', slug=comment.post.slug)
        # return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def post_view(request):
    user_id = request.GET.get('user')
    if user_id:
        posts = Post.objects.filter(user_id=user_id)
    else:
        posts = Post.objects.all()
    return render(request, 'posts/feed.html', {'posts': posts})

posts/templates/posts/detail.html
{% extends 'users/base.html' %}
{% load mathfilters%}
{% block body %}
<div class="flex mt-5 p-10 justify-center">
    <h1 class="text-3xl font-normal mb-2 text-gray-500">My Posts</h1>
</div>
<!-- <div class="grid mx-60 p-10 grid-cols-1 justify-center"> -->
  <div>
    <div class="rounded overflow-hidden w-[470px] h-[470px] bg-gray-200 shadow-lg p-10 m-10">
      <div class="user-container flex mx-5 my-2 items-center">
        <a href="/posts/view?user={{ post.user.id }}" id="user-posts-link">
          <img class="h-20 w-20 rounded-full" src="{{post.user.profile.photo.url}}" alt="">
          <div class="mx-2 my-2 font-bold"><span class="text-indigo-500">{{post.user}}</span></div>
        </a> 
        {% for cat in post.categories.all %}
            <div class="font-bold text-3xl mx-5 my-2">{{cat.title}}:  </div>
          {% endfor %}
        <div class="font-bold text-3xl mx-2 my-2"><a href="{% url 'detail' post.id %}">-- {{post.title}} --</a></div>
        
      </div>
      <hr>
      <div class="mx-2 my-2 postBody">{{post.body|slice:":200"}}</div>
      {% if post.body|length > 200 %}
        <a class="more-button">continue reading..</a>
        <div class="post-rest" style="display: none;">{{ post.body|slice:"200:" }}</div>
      {% endif %}
      {% if post.images %}
        {% for image in post.images.all%} 
      <div class="justify-center" style="justify-content: center;">
          <img class="h-70 px-20" src="{{ image.images.url }}" alt="" style="height: 50%;">
          <div id="{{post.id}}"></div>
          <div class="mx-2 my-2">{{image.caption|slice:":200"}}</div>
          {% if image.caption|length > 200 %}
          <a class="more-button">continue reading..</a>
        <div class="post-rest" style="display: none;">{{ image.caption|slice:"200:" }}</div>
      {% endif %}
        </div>
        {% endfor %}
      {% endif %}

      {% with tags=post.tags.exists %}
        {% if tags %}
            {% for tag in post.tags.all %}
                <p>Tags: {{ tag }}</p>
            {% endfor %}
        {% else %}
            <p>Tags: No tags</p>
        {% endif %}
      {% endwith %}
      <a><div class="py-2" data-toggle="modal" data-target="#myModal-{{post.id}}">
        {% if request.user in post.liked_by.all %}
            {% if post.liked_by.count < 1 %}
            {% elif post.liked_by.count == 1 %}
            You like this
            {% elif post.liked_by.count > 1 %}
            You & {{ post.liked_by.count|sub:1 }} Like this
            
            {% endif %}
        {% else %}
            {% if post.liked_by.count < 1 %}
            {% elif post.liked_by.count == 1 %}
            {{ post.liked_by.first }} Likes this
            {% elif post.liked_by.count > 1 %}
            {{ post.liked_by.first }} & {{ post.liked_by.count|sub:1 }} like this
            {% endif %}
        {% endif %}
      </div></a>
      <div class="px-6">
          
          <hr>
          <!-- <div>
              <p>Likes: {{ post.liked_by.all|length }}</p>
              
          </div> -->
        <div class="icon-container flex gap-3 py-1" id="likeSection">
              {% if request.user in post.liked_by.all %}
              <a href="{% url 'like' id=post.id %}#{{ post.id }}" class="button-like"><i class="fa-solid fa-heart" style="color: red;"></i></a>
              <!-- <a onclick="window.location.href='{% url 'like' id=post.id %}'" class="button-like"><i class="fa-solid fa-heart" style="color: red;"></i></a> -->
              {% else %}
              <a href="{% url 'like' id=post.id %}#{{ post.id }}" class="button-like" ><i class="fa-regular fa-heart"></i></a>
              <!-- <a onclick="window.location.href='{% url 'like' id=post.id %}'" class="button-like"><i class="fa-regular fa-heart"></i></a> -->
              {% endif %}
              <a href="#{{ post.id }}" onclick="toggleCommentForm('comment-form-{{post.id}}')">
                <i class="fa-regular fa-message"></i>
              </a>
              <a>
                  <i class="fa-solid fa-share"></i>
              </a>
          </div>
          <hr>
          <!-- Modal -->
          <div class="modal fade" id="myModal-{{post.id}}" role="dialog">
            <div class="modal-dialog modal-dialog-scrollable">

              <div class="modal-content">
                <div class="modal-header bg-primary">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h4 class="modal-title">Post liked by: </h4>
                </div>
                <div class="modal-body">
                  {% for name in post.liked_by.all%}
                    <p>{{name}}</p>
                  {% endfor %}
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
          <div class="px-5 py-5" id="comment-form-{{post.id}}" style="display: none;">
            <form method="post" class="bg-white shadow-md m-10 w-4/5 rounded px-8 pt-6 pb-8 mb-4">
              {% csrf_token %}
              
                <div class="m-2">
                  <label class="block text-grey-700 text-sm font-bold mb-2">Add Comment</label>
                </div>
                <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-grey-700">
                  <!-- {{comment_form.body}} -->
                  <textarea name="body" style="width: 100%; max-width: 100%;" required id="id_body"></textarea>
                </div>
                <div>
                  <input type="hidden" name="post_id" id="post_id" value="{{ post.id }}">
                  <input type="hidden" name="posted_by" id="posted_by" value="{{ logged_user }}">
                </div>
                  <button class="bg-green-500 text-white px-5 py-2" type="submit" id="comment-button">Add</button>
              
            </form>
          </div>

          <!-- <div class="nothing">
              {% for name in post.liked_by.all%}
              <p>{{name}}</p>
            {% endfor %}
          </div> -->

          <!-- Scrollable modal -->



            </div>
            <div class="px-5 py-5">
              
            {% for comment in post.comments.all %}
            <p><b>{{comment.posted_by}}</b>: {{ comment.body }} </p>
            <div class="icon-container flex gap-3 py-1" id="likeSection">
              {% if request.user in post.liked_by.all %}
              <a href="{% url 'like' id=post.id %}#{{ post.id }}" class="button-like"><i class="fa-solid fa-heart" style="color: red;"></i></a>
              <!-- <a onclick="window.location.href='{% url 'like' id=post.id %}'" class="button-like"><i class="fa-solid fa-heart" style="color: red;"></i></a> -->
              {% else %}
              <a href="{% url 'like' id=post.id %}#{{ post.id }}" class="button-like" ><i class="fa-regular fa-heart"></i></a>
              <!-- <a onclick="window.location.href='{% url 'like' id=post.id %}'" class="button-like"><i class="fa-regular fa-heart"></i></a> -->
              {% endif %}
              <a href="#{{ post.id }}" onclick="toggleCommentForm('reply-form-{{comment.id}}')">
                <i class="fa-regular fa-message"></i>
              </a>
              <a>
                  <i class="fa-solid fa-share"></i>
              </a>
          </div>
              <div class="pl-10 py-5">
                <!-- <h1>The Replies</h1> -->
          {% for reply in comment.replies.all %}
              <div class="reply">
                  <p><b>{{ reply.posted_by }}: </b>{{ reply.body }}</p>
              </div>
          {% endfor %}
          </div>
          <hr>
           <div id="reply-form-{{comment.id}}" style="display: none;">
            <form method="post" class="bg-white shadow-md m-10 w-4/5 rounded px-8 pt-6 pb-8 mb-4" action="{% url 'add_reply' comment.id %}">
                {% csrf_token %}
                
                <div class="m-2">
                    <label class="block text-grey-700 text-sm font-bold mb-2">Add Reply</label>
                </div>
                <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-grey-700">
                    <!-- {{reply_form.body}} -->
                    <textarea name="body" style="width: 100%; max-width: 100%;" required id="reply"></textarea>
                </div>
                <div>
                    <!-- <input type="hidden" name="comment_id" id="comment_id" value="{{ comment.id }}"> -->
                    <input type="hidden" name="posted_by" id="posted_by" value="{{ logged_user }}">
                </div>
                <button class="bg-green-500 text-white px-5 py-2" type="submit" id="reply-button">Add</button>
            </form>
        </div>
            {% endfor %}
            </div>
            
  </div>

  </div>
</div>

</div>

{% endblock %}
<!-- <h1>{{ post.title }}</h1>
<p>{{ post.body }}</p>
{% if post.images %}
            {% for image in post.images.all%} 
          <div class="justify-center" style="justify-content: center;">
              <img class="h-70 px-20" src="{{ image.images.url }}" alt="" style="height: 50%;">
              <div class="mx-2 my-2">{{image.caption}}</div>
            </div>
            {% endfor %}
          {% endif %} -->

posts/templates/posts/feed.html
{% extends 'users/base.html' %}
{% load hitcount_tags %}
{% load mathfilters%}
{% block body %}
<div class="flex mt-5 p-10 justify-center">
    <h1 class="text-3xl font-normal mb-2 text-gray-500">All Posts</h1>
</div>
<!-- <div class="grid mx-60 p-10 grid-cols-1 justify-center"> -->
  <div>
    {% for post in posts %}
        
    <div class="rounded overflow-hidden w-[470px] h-[470px] bg-gray-200 shadow-lg p-10 m-10">
      <div class="user-container flex mx-5 my-2 items-center">
        <a href="/posts/view?user={{ post.user.id }}" id="user-posts-link">
          <img class="h-20 w-20 rounded-full" src="{{post.user.profile.photo.url}}" alt="">
          <div class="mx-2 my-2 font-bold"><span class="text-indigo-500">{{post.user}}</span></div>
        </a> 
        {% for category in post.categories.all %}
            <div class="font-bold text-3xl mx-5 my-2">
              <h2><a href="{% url 'category_detail' slug=category.slug %}">{{ category.title }}: </a></h2>
            </div>
          {% endfor %}
        <div class="font-bold text-3xl mx-2 my-2"><a href="{% url 'detail' post.slug %}">-- {{post.title}} --</a></div>
          
      </div>
      <hr>
      <div class="mx-2 my-2 postBody" class="text-decoration-none"><a href="{% url 'detail' post.slug %}">{{post.body|slice:":200"}}</a></div>
      {% if post.body|length > 200 %}
        <!-- <a class="more-button">continue reading..</a> -->
        <div class="post-rest text-decoration-none">{{ post.body|slice:"200:" }}</div>
      {% endif %}
      <hr class="divider">
      <!-- {% if post.images %}
        {% for image in post.images.all%} 
      <div class="justify-center" style="justify-content: center;">
          <img class="h-70 px-20" src="{{ image.images.url }}" alt="" style="height: 50%;">
          <div id="{{post.id}}"></div>
          <div class="mx-2 my-2">{{image.caption|slice:":200"}}</div>
          {% if image.caption|length > 200 %}
          <a class="more-button">continue reading..</a>
        <div class="post-rest" style="display: none;">{{ image.caption|slice:"200:" }}</div>
      {% endif %}
        </div>
        {% endfor %}
      {% endif %} -->
      <div id="{{post.id}}"></div>
      {% with tags=post.tags.exists %}
        {% if tags %}
            {% for tag in post.tags.all %}
                <p>Tags: {{ tag }}</p>
            {% endfor %}
        {% else %}
            <p>Tags: No tags</p>
        {% endif %}
      {% endwith %}
      <!-- <a><div class="py-2" data-toggle="modal" data-target="#myModal-{{post.id}}">
        {% if request.user in post.liked_by.all %}
            {% if post.liked_by.count < 1 %}
            {% elif post.liked_by.count == 1 %}
            You like this
            {% elif post.liked_by.count > 1 %}
            You & {{ post.liked_by.count|sub:1 }} Like this
            
            {% endif %}
        {% else %}
            {% if post.liked_by.count < 1 %}
            {% elif post.liked_by.count == 1 %}
            {{ post.liked_by.first }} Likes this
            {% elif post.liked_by.count > 1 %}
            {{ post.liked_by.first }} & {{ post.liked_by.count|sub:1 }} like this
            {% endif %}
        {% endif %}
      </div></a> -->
      <hr class="divider">
      <div class="px-6">
          
          <hr>
          <div>
              
              
          </div>
        <div class="icon-container flex gap-3 py-1">
              <!-- {% if request.user in post.liked_by.all %}
              <a href="{% url 'like' id=post.id %}#{{ post.id }}" class="button-like"><i class="fa-solid fa-heart" style="color: red;"></i></a> -->
              <!-- <a onclick="window.location.href='{% url 'like' id=post.id %}'" class="button-like"><i class="fa-solid fa-heart" style="color: red;"></i></a> -->
              <!-- {% else %}
              <a href="{% url 'like' id=post.id %}#{{ post.id }}" class="button-like" ><i class="fa-regular fa-heart"></i></a> -->
              <!-- <a onclick="window.location.href='{% url 'like' id=post.id %}'" class="button-like"><i class="fa-regular fa-heart"></i></a> -->
              <!-- {% endif %} -->
              <a href="{% url 'detail' post.slug %}#{{ likeSection }}">
                <p>{% if post.liked_by.count < 1 %}
                <i class="fa-regular fa-heart"></i><span style="color: rgb(53, 52, 52);" class="mr-10">{{ post.liked_by.all|length }} likes</span>
                {% else %}
               <i class="fa-solid fa-heart" style="color: red;"></i><span style="color: rgb(53, 52, 52);" class="mr-10">{{ post.liked_by.all|length }} likes</span>
              {% endif %}
                <!-- <a href="#{{ post.id }}" onclick="toggleCommentForm('comment-form-{{post.id}}')"> -->
                <i class="fa-regular fa-message"></i> <span style="color: rgb(53, 52, 52);" class="mr-10">{{post.comments.all|length}} comments</span>
              <!-- </a> -->
              <!-- <a> -->
                <i class="fa-solid fa-eye"></i> <span style="color: rgb(53, 52, 52);" class="mr-10">{% get_hit_count for post %} views</span>
                  <!-- <i class="fa-solid fa-share" ></i> -->
              <!-- </a> -->
            </p>
            </a>
          </div>
          <hr>
          <!-- Modal -->
          <!-- <div class="modal fade" id="myModal-{{post.id}}" role="dialog">
            <div class="modal-dialog modal-dialog-scrollable">

              <div class="modal-content">
                <div class="modal-header bg-primary">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h4 class="modal-title">Post liked by: </h4>
                </div>
                <div class="modal-body">
                  {% for name in post.liked_by.all%}
                    <p>{{name}}</p>
                  {% endfor %}
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div> -->

          <!-- <div class="nothing">
              {% for name in post.liked_by.all%}
              <p>{{name}}</p>
            {% endfor %}
          </div> -->

          <!-- Scrollable modal -->



            <!-- </div>
            <div class="px-5 py-5">
            {% for comment in post.comments.all %}
            <p><b>{{comment.posted_by}}</b>: {{ comment.body }} </p>
            {% for reply in comment.replies.all %}
              <div class="pl-10 py-5 reply">
                  {{ reply.body }} - {{ reply.posted_by }}
              </div>
          {% endfor %}
            <div class="px-5 py-5" id="reply-form-{{comment.id}}">
              <form method="post" class="bg-white shadow-md m-10 w-4/5 rounded px-8 pt-6 pb-8 mb-4" action="{% url 'add_feed_reply' comment.id %}">
                {% csrf_token %}
                
                <div class="m-2">
                    <label class="block text-grey-700 text-sm font-bold mb-2">Add Reply</label>
                </div>
                <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-grey-700"> -->
                    <!-- {{reply_form.body}} -->
                    <!-- <textarea name="body" style="width: 100%; max-width: 100%;" required id="reply"></textarea>
                </div>
                <div> -->
                    <!-- <input type="hidden" name="comment_id" id="comment_id" value="{{ comment.id }}"> -->
                    <!-- <input type="hidden" name="posted_by" id="posted_by" value="{{ logged_user }}">
                </div>
                <button class="bg-green-500 text-white px-5 py-2" type="submit" id="reply-button" onclick="location.href='#reply-form-{{ comment.id }}'">Add</button>
            </form>
          </div>-->
   
          
            <!-- {% endfor %}
            </div>
            <div class="px-5 py-5" id="comment-form-{{post.id}}" style="display: none;">
              <form method="post" class="bg-white shadow-md m-10 w-4/5 rounded px-8 pt-6 pb-8 mb-4">
                {% csrf_token %}
                
                  <div class="m-2">
                    <label class="block text-grey-700 text-sm font-bold mb-2">Add Comment</label>
                  </div>
                  <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-grey-700"> -->
                    <!-- {{comment_form.body}} -->
                    <!-- <textarea name="body" style="width: 100%; max-width: 100%;" required id="id_body"></textarea>
                  </div>
                  <div>
                    <input type="hidden" name="post_id" id="post_id" value="{{ post.id }}">
                    <input type="hidden" name="posted_by" id="posted_by" value="{{ logged_user }}">
                  </div>
                    <button class="bg-green-500 text-white px-5 py-2" type="submit" id="comment-button">Add</button>
                
              </form>
            </div> -->
  </div>

  </div>
</div> 

{% endfor %}
</div>

{% endblock %}